apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zfr2uu5el-go 
  janus-idp.io/tekton: zfr2uu5el-go
  backstage.io/kubernetes-id: zfr2uu5el-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zfr2uu5el-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml